services:
  postgres:
    image: postgres:18

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  bronze:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    working_dir: /app

    volumes:
      - .:/app
      - spark_ivy:/tmp/.ivy2

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --repositories
      - https://repo.maven.apache.org/maven2
      - --packages
      - org.postgresql:postgresql:42.7.8
      - /app/bronze/main.py


volumes:
  postgres_data:
  spark_ivy: